feat(docs): Add basic example docs gen + perfetto deep linking.

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -71,7 +71,7 @@ jobs:
   # ===--------------------------------------------------------------------=== #
   # SystemVerilog format check
   # ===--------------------------------------------------------------------=== #
-  sytemverilog-fmt:
+  systemverilog-fmt:
     runs-on: ubuntu-latest
     env:
       VERIBLE_VERSION: v0.0-4017-g62aee204
@@ -135,6 +135,13 @@ jobs:
         run: |
           uv run ./examples/run.py
 
+      - name: Upload example traces (for docs)
+        uses: actions/upload-artifact@v4
+        with:
+          name: examples-out
+          path: examples/out/
+          retention-days: 0.1
+
       - name: Run integration tests
         run: ./test/test.bash
 
@@ -144,8 +151,20 @@ jobs:
 
   docs:
     runs-on: ubuntu-latest
+    needs: integration
     steps:
       - uses: actions/checkout@v4
+
+      - name: Download examples output (from integration test)
+        uses: actions/download-artifact@v4
+        with:
+          name: examples-out
+          path: examples/out/
+
+      - name: Install uv
+        uses: astral-sh/setup-uv@v6
+        with:
+          enable-cache: true
 
       - name: install mdbook
         env:
@@ -180,9 +199,16 @@ jobs:
 
       - name: Build documentation
         run: |
-          PATH=$PATH:$HOME/bin ls ~/bin
-          PATH=$PATH:$HOME/bin which mdbook-alerts
-          PATH=$PATH:$HOME/bin mdbook build
+          PATH=$PATH:$HOME/bin CSPECT_DOCS_STRICT=1 mdbook build
+
+      - name: Check for example_missing.html
+        run: |
+          if [ -f "build/mdbook/html/examples_missing.html" ]; then
+            echo "❌ Build failed: examples_missing.html file exists"
+            exit 1
+          else
+            echo "✅ No missing examples detected"
+          fi
 
       - name: Upload artifact
         if: github.event_name == 'push'
@@ -205,7 +231,7 @@ jobs:
       pages: write
       id-token: write
     if: github.event_name == 'push'
-    needs: ["docs", "integration"]
+    needs: ["docs", "integration", "rust-checks", "python-fmt", "systemverilog-fmt"]
     steps:
       - name: Deploy to GitHub Pages
         id: deployment
